NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3",
"GAENZLGHJGJRCMX5VCHOLHQXU3EMCU5XWDNU4BGGJFNLI2EL354IVBK7",
"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="udin.xyz"
ORG_DBA="UDIN token"
ORG_URL="https://udin.xyz"
ORG_LOGO="https://udin.xyz/assets/udin.png"
ORG_DESCRIPTION="mang udin"
ORG_PHYSICAL_ADDRESS="soon"
ORG_KEYBASE="accountname"
ORG_TWITTER="udinxyz"
ORG_GITHUB="udinxyz"
ORG_OFFICIAL_EMAIL="soon"

[[CURRENCIES]]
code = "UDIN"
name = "UDIN"
issuer = "GARBCYGT5TO4Z5WCYNOJX53ZR4ZELBY5ZAYK6DKOABRL26P44KBISOJC"
is_asset_anchored = false
display_decimals = 7
desc="UDIN Token"
image="https://udin.xyz/assets/udintoken.png"
conditions="There will only ever be 1 billion UDIN tokens in existence."
